#!/usr/bin/env python3
"""Bootstrap an Obsidian vault as an LLM-wiki workspace.

Author: Ibrahim AbuAlhaol

Run this straight after cloning the skill into your vault's agent directory:

    mkdir -p ~/brain && cd ~/brain
    git init
    git clone <repo> .claude/skills/my-llm-wiki
    python .claude/skills/my-llm-wiki/scripts/init_vault.py

It infers the vault root from its own location, so it normally needs no
arguments. What it does:

  * verifies the vault is a git repo (Hermes needs .git to find project skills)
  * renames the skill in SKILL.md frontmatter to match its directory
  * creates raw/ and wiki/, the +/ inbox, and assets/
  * copies guides/guide.md into the vault as Systems/vault-guide.md and creates
    the folders it lists (edit the guide *before* running this), and puts the
    guide, rendered as styled HTML, at the vault root as GUIDE.html (rebuilt
    from the vault's own guide on every run, so it follows your edits)
  * seeds HOME.md and ME.md at the vault root for the human to fill in
  * exposes the skill in .agents/, .claude/ and .gemini/skills/ (symlink,
    junction, or copy), which between them reach Claude Code, Gemini CLI,
    OpenCode, Hermes and Pi
  * installs the /fetch, /ingest, /organize and /vault-status commands for all five: command
    files for Claude Code, OpenCode, Gemini CLI and Pi, small skills for Hermes

Re-run it after updating the skill to re-sync: links are always current, and
every file it generated (commands, copied skills) carries a stamp and is
refreshed. Files without the stamp are yours and are never touched.
  * writes a .gitignore that keeps Obsidian's churn out of history
  * prints the remaining manual steps

Apart from the folders and the vault guide, everything it creates lives in
dot-directories, which Obsidian does not index.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# Agent directories that can hold a project-local skill, and which agents read
# them. Sourced from each tool's docs; see README.md for links.
AGENT_DIRS = {
    ".agents/skills": ("OpenCode", "Hermes", "Pi", "Gemini CLI"),
    ".claude/skills": ("Claude Code", "OpenCode"),
    ".gemini/skills": ("Gemini CLI",),
    ".hermes/skills": ("Hermes",),
    ".opencode/skills": ("OpenCode",),
    ".pi/skills": ("Pi",),
}

# Between them these three cover every supported agent, so the bootstrapper makes
# the skill reachable from all of them no matter which one you cloned into.
EXPOSE_DIRS = (".agents/skills", ".claude/skills", ".gemini/skills")

# Where the vault guide ships inside the skill, and where it lands in the vault.
# The vault copy is visible in Obsidian on purpose: the human reads it too.
GUIDE_SOURCE = Path("guides/guide.md")
GUIDE_TARGET = Path("Systems/vault-guide.md")

# Files the human keeps at the vault root, seeded once and never overwritten:
# a styled copy of the guide to keep the conventions in view, and the two notes
# the human maintains for the agent (see SKILL.md, "HOME.md and ME.md").
GUIDE_HTML = Path("GUIDE.html")
HUMAN_FILES = (
    ("HOME.md", Path("references/home-template.md")),
    ("ME.md", Path("references/me-template.md")),
)

# Slash commands ship in the skill as markdown with a `description:` frontmatter
# line, `{{skill}}` for the skill's name and `$ARGUMENTS` for what follows the
# command. Each agent gets them in its own project command directory, in its
# own format. Hermes has no command files: every skill is a slash command, so
# each command becomes a small skill there.
COMMANDS_SOURCE = Path("commands")
COMMAND_DIRS = {
    ".claude/commands": ("Claude Code", "md"),
    ".opencode/commands": ("OpenCode", "md"),
    ".gemini/commands": ("Gemini CLI", "toml"),
    ".pi/prompts": ("Pi", "md"),
    ".hermes/skills": ("Hermes", "skill"),
}

# Stamped into every file the bootstrapper generates. Re-running it refreshes
# stamped files and leaves unstamped ones (the human's own) alone; deleting the
# stamp line is how the human keeps an edited copy.
STAMP = "generated by init_vault.py"
COPY_STAMP = ".init-vault-copy"

# What Hermes gets in place of $ARGUMENTS: its skill commands pass the rest of
# the message along instead of substituting a placeholder.
HERMES_ARGS = "the text the user typed after the command (none if nothing)"

# Folders the skill's own workflows need, whether or not a guide lists them.
# The inbox keeps a .gitkeep so git tracks it while it is empty.
INBOX = "+"
SKILL_DIRS = ("raw", "wiki", INBOX, "assets")

# A folder line in the guide's "Folder Hierarchy" block, e.g. "  /Areas/Day-Job".
FOLDER_LINE_RE = re.compile(r"^\s*/([^\s/][^\s]*?)/?\s*$")

# OpenCode enforces this on the frontmatter name, and requires it to match the
# skill's directory name.
NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

GITIGNORE = """\
# Obsidian: per-machine UI state, not knowledge. Keep the rest of .obsidian/
# (your plugins and settings) versioned.
.obsidian/workspace.json
.obsidian/workspace-mobile.json
.obsidian/cache

# OS noise
.DS_Store
Thumbs.db

# Python bytecode from the skill's scripts
__pycache__/
*.pyc
"""


class Abort(Exception):
    pass


def run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)


def find_skill_root(start: Path) -> Path:
    """Walk up from this file to the directory containing SKILL.md."""
    for candidate in [start, *start.parents]:
        if (candidate / "SKILL.md").is_file():
            return candidate
    raise Abort(f"No SKILL.md found at or above {start}")


def find_vault_root(skill_root: Path) -> tuple[Path, str]:
    """Infer the vault from a skill living in <vault>/<agent-dir>/<name>."""
    for agent_dir in AGENT_DIRS:
        depth = len(Path(agent_dir).parts)  # e.g. ".claude/skills" -> 2
        try:
            vault = skill_root.parents[depth]
        except IndexError:
            continue
        if skill_root.parent == vault / agent_dir:
            return vault, agent_dir
    raise Abort(
        f"{skill_root} is not inside a recognized agent directory.\n"
        f"Expected <vault>/<{'|'.join(AGENT_DIRS)}>/<skill-name>.\n"
        "Move the clone there, or pass --vault to override."
    )


def ensure_git(vault: Path, do_init: bool) -> str:
    if (vault / ".git").exists():
        return "already a git repo"
    if not do_init:
        raise Abort(
            f"{vault} is not a git repo.\n"
            "Hermes locates project skills by finding the nearest ancestor with "
            ".git, so without it Hermes will not see this skill.\n"
            "Run `git init` there yourself, or drop --no-git-init and this "
            "script will do it."
        )
    result = run(["git", "init"], vault)
    if result.returncode != 0:
        raise Abort(f"git init failed: {result.stderr.strip()}")
    return "initialized"


def rename_skill(skill_root: Path) -> str:
    """Make the frontmatter name match the directory name."""
    dir_name = skill_root.name
    if not NAME_RE.match(dir_name) or len(dir_name) > 64:
        raise Abort(
            f"Directory name {dir_name!r} is not a valid skill name.\n"
            "Use lowercase letters, digits and single hyphens (max 64 chars), "
            "e.g. ibrahim-llm-wiki."
        )

    skill_md = skill_root / "SKILL.md"
    text = skill_md.read_text(encoding="utf-8")
    match = re.search(r"^name:[ \t]*(.+?)[ \t]*$", text, re.MULTILINE)
    if not match:
        raise Abort(f"No `name:` field in {skill_md}")

    current = match.group(1).strip()
    if current == dir_name:
        return f"already {dir_name}"

    text = text[: match.start()] + f"name: {dir_name}" + text[match.end() :]

    # Keep the skill discoverable under its new name by adding it as a trigger.
    desc = re.search(r'^description:[ \t]*"(.*)"[ \t]*$', text, re.MULTILINE)
    if desc and dir_name not in desc.group(1):
        body = desc.group(1).rstrip()
        body = body[:-1] if body.endswith(".") else body
        text = (
            text[: desc.start()]
            + f'description: "{body}, or \'{dir_name}\'."'
            + text[desc.end() :]
        )

    skill_md.write_text(text, encoding="utf-8")
    return f"{current} -> {dir_name}"


def guide_folders(text: str) -> list[str]:
    """Folder paths listed in the first code block under "## Folder Hierarchy"."""
    section = re.search(
        r"^##\s+Folder Hierarchy\s*$(.*?)(?=^##\s|\Z)", text, re.M | re.S
    )
    if not section:
        return []
    block = re.search(r"^```[^\n]*\n(.*?)^```", section.group(1), re.M | re.S)
    if not block:
        return []
    folders = []
    for line in block.group(1).splitlines():
        match = FOLDER_LINE_RE.match(line)
        if match and ".." not in match.group(1).split("/"):
            folders.append(match.group(1))
    return folders


def install_guide(vault: Path, skill_root: Path, source: Path | None) -> list[tuple[str, str]]:
    """Copy the vault guide in (never overwriting) and create its folders.

    Folders come from the vault copy when it already exists, so re-running
    after editing the guide in Obsidian picks up new folders.
    """
    steps: list[tuple[str, str]] = []
    target = vault / GUIDE_TARGET
    label = str(GUIDE_TARGET).replace(os.sep, "/")

    if target.is_file():
        steps.append((label, "left alone (already exists; folders read from it)"))
    else:
        source = source or skill_root / GUIDE_SOURCE
        if not source.is_file():
            steps.append((label, f"skipped (no guide at {source})"))
            return steps
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        steps.append((label, "created"))

    created = []
    for folder in guide_folders(target.read_text(encoding="utf-8")):
        path = vault / folder
        if not path.is_dir():
            path.mkdir(parents=True)
            created.append(folder)
    steps.append(
        ("guide folders", ", ".join(f"{f}/" for f in created) if created else "all present")
    )
    return steps


def load_script(name: str):
    """Import a sibling script as a module (they are standalone, not a package)."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(name, Path(__file__).resolve().parent / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def install_guide_html(vault: Path) -> tuple[str, str]:
    """Render the vault's guide as GUIDE.html, refreshed while it carries the stamp."""
    guide = vault / GUIDE_TARGET
    if not guide.is_file():
        return (GUIDE_HTML.name, f"skipped (no {GUIDE_TARGET.as_posix()})")
    stamp = (
        f"{STAMP} from {GUIDE_TARGET.as_posix()}; edit the guide, then re-run it "
        "to rebuild this page"
    )
    html = load_script("build_guide").render(guide.read_text(encoding="utf-8"), stamp)
    state = sync_file(vault / GUIDE_HTML, html)
    labels = {"kept": "left alone (yours: no stamp)", "current": "up to date"}
    return (GUIDE_HTML.name, labels.get(state, state))


def install_root_files(
    vault: Path, skill_root: Path, files: tuple[tuple[str, Path], ...]
) -> list[tuple[str, str]]:
    """Seed files at the vault root from the skill, never overwriting."""
    steps: list[tuple[str, str]] = []
    for name, source in files:
        target = vault / name
        if target.exists():
            steps.append((name, "left alone (already exists)"))
        elif not (skill_root / source).is_file():
            steps.append((name, f"skipped (no {source.as_posix()} in the skill)"))
        else:
            shutil.copyfile(skill_root / source, target)
            steps.append((name, "created"))
    return steps


def render_command(text: str, skill_name: str, fmt: str, command: str = "") -> str:
    """Fill in the skill name, convert to the agent's format, and stamp it.

    fmt is "md" (Claude Code, OpenCode, Pi), "toml" (Gemini CLI), or "skill"
    (a SKILL.md for Hermes, named after `command`).
    """
    # Normalize line endings: a Windows checkout may hand us CRLF.
    text = text.replace("\r\n", "\n").replace("{{skill}}", skill_name)
    match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not match:
        raise Abort("command template is missing its frontmatter")
    frontmatter, body = match.group(1), match.group(2).strip()
    desc = re.search(r"^description:[ \t]*(.+?)[ \t]*$", frontmatter, re.M)
    description = desc.group(1) if desc else ""
    stamp = f"{STAMP} from the {skill_name} skill; re-run it to update, or delete this line to keep your edits"

    if fmt == "md":
        return f"---\n{frontmatter}\n---\n\n<!-- {stamp} -->\n\n{body}\n"
    if fmt == "skill":
        body = body.replace("$ARGUMENTS", HERMES_ARGS)
        return (
            f"---\nname: {command}\ndescription: \"{description.replace(chr(34), chr(39))}\"\n---\n\n"
            f"<!-- {stamp} -->\n\n{body}\n"
        )

    body = body.replace("$ARGUMENTS", "{{args}}")
    # A TOML literal string: no escapes, so the prompt is stored exactly.
    if "'''" in body:
        raise Abort("command template body cannot contain '''")
    description = description.replace("\\", "\\\\").replace('"', '\\"')
    return f"# {stamp}\ndescription = \"{description}\"\n\nprompt = '''\n{body}\n'''\n"


def sync_file(target: Path, text: str) -> str:
    """Write a generated file: create it, refresh it if stamped, else leave it."""
    if not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        return "created"
    current = target.read_text(encoding="utf-8", errors="replace")
    if STAMP not in current:
        return "kept"
    if current == text:
        return "current"
    target.write_text(text, encoding="utf-8")
    return "updated"


def install_commands(vault: Path, skill_root: Path) -> list[tuple[str, str]]:
    """Put every command in every agent's command directory, kept in sync."""
    sources = sorted((skill_root / COMMANDS_SOURCE).glob("*.md"))
    if not sources:
        return [("commands", f"skipped (no {COMMANDS_SOURCE}/ in the skill)")]

    labels = {
        "created": "created",
        "updated": "updated",
        "current": "up to date",
        "kept": "left alone (yours: no stamp)",
    }
    steps: list[tuple[str, str]] = []
    for agent_dir, (agent, fmt) in COMMAND_DIRS.items():
        outcome: dict[str, list[str]] = {}
        for source in sources:
            name = source.stem
            if fmt == "skill":
                target = vault / agent_dir / name / "SKILL.md"
            else:
                target = vault / agent_dir / f"{name}.{fmt}"
            text = render_command(source.read_text(encoding="utf-8"), skill_root.name, fmt, name)
            outcome.setdefault(sync_file(target, text), []).append(f"/{name}")
        detail = "; ".join(
            f"{', '.join(names)} {labels[state]}" for state, names in outcome.items()
        )
        steps.append((f"{agent_dir}/", f"{detail}  [{agent}]"))
    return steps


def expose_in(vault: Path, skill_root: Path, agent_dir: str) -> str:
    """Make the skill reachable from <vault>/<agent_dir>/<name>.

    Prefers a symlink, falls back to a Windows junction, and copies only as a
    last resort. A link is always in sync; a copy is stamped so that re-running
    this script refreshes it. Returns a human-readable description.
    """
    target = vault / Path(agent_dir) / skill_root.name

    if target == skill_root:
        return "the install itself"
    if (target / COPY_STAMP).is_file():
        shutil.rmtree(target)
        copy_skill(skill_root, target)
        return "copy refreshed"
    if target.exists() and target.resolve() == skill_root.resolve():
        return "linked (always in sync)"
    if target.exists() or target.is_symlink():
        return "left alone (a different directory is already there)"

    target.parent.mkdir(parents=True, exist_ok=True)
    relative = os.path.relpath(skill_root, target.parent)

    try:
        os.symlink(relative, target, target_is_directory=True)
        return f"symlink -> {relative}"
    except (OSError, NotImplementedError):
        pass

    if os.name == "nt":
        # Junctions need no admin rights or Developer Mode, unlike symlinks.
        result = subprocess.run(
            ["cmd", "/c", "mklink", "/J", str(target), str(skill_root)],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return f"junction -> {relative}"

    copy_skill(skill_root, target)
    return "copied (no link support; re-run this script after editing the skill)"


def copy_skill(skill_root: Path, target: Path) -> None:
    shutil.copytree(skill_root, target, ignore=shutil.ignore_patterns(".git", "__pycache__"))
    (target / COPY_STAMP).write_text(
        f"{STAMP}: a copy of {skill_root.name}, refreshed on every re-run\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bootstrap an Obsidian vault as an LLM-wiki workspace."
    )
    parser.add_argument(
        "--vault",
        type=Path,
        help="Vault root. Inferred from this script's location by default.",
    )
    parser.add_argument(
        "--no-git-init",
        dest="git_init",
        action="store_false",
        help="Fail instead of running `git init` when the vault is not a repo.",
    )
    parser.add_argument(
        "--no-link",
        dest="link",
        action="store_false",
        help=(
            "Install only where the skill was cloned, instead of exposing it "
            "from both .agents/skills/ and .claude/skills/."
        ),
    )
    parser.add_argument(
        "--guide",
        type=Path,
        help=f"Vault guide to install. Defaults to {GUIDE_SOURCE} in the skill.",
    )
    parser.add_argument(
        "--no-guide",
        dest="install_guide",
        action="store_false",
        help=f"Do not install {GUIDE_TARGET}, {GUIDE_HTML}, or the guide's folders.",
    )
    parser.add_argument(
        "--no-commands",
        dest="install_commands",
        action="store_false",
        help="Do not install the /fetch, /ingest, /organize and /vault-status slash commands.",
    )
    args = parser.parse_args()

    try:
        skill_root = find_skill_root(Path(__file__).resolve().parent)

        if args.vault:
            vault = args.vault.resolve()
            installed_in = (
                str(skill_root.parent.relative_to(vault)).replace(os.sep, "/")
                if skill_root.is_relative_to(vault)
                else "(outside vault)"
            )
        else:
            vault, installed_in = find_vault_root(skill_root)

        steps: list[tuple[str, str]] = []
        steps.append(("vault", str(vault)))
        steps.append(("skill", f"{installed_in}/{skill_root.name}"))
        steps.append(("git", ensure_git(vault, args.git_init)))
        steps.append(("skill name", rename_skill(skill_root)))

        for name in SKILL_DIRS:
            path = vault / name
            existed = path.is_dir()
            path.mkdir(exist_ok=True)
            if name == INBOX:
                (path / ".gitkeep").touch()
            steps.append((f"{name}/", "already existed" if existed else "created"))

        if args.link:
            for agent_dir in EXPOSE_DIRS:
                agents = ", ".join(AGENT_DIRS[agent_dir])
                steps.append(
                    (
                        f"{agent_dir}/",
                        f"{expose_in(vault, skill_root, agent_dir)}  [{agents}]",
                    )
                )

        if args.install_guide:
            steps.extend(install_guide(vault, skill_root, args.guide))
            steps.append(install_guide_html(vault))

        steps.extend(install_root_files(vault, skill_root, HUMAN_FILES))

        if args.install_commands:
            steps.extend(install_commands(vault, skill_root))

        gitignore = vault / ".gitignore"
        if gitignore.exists():
            steps.append((".gitignore", "left alone (already exists)"))
        else:
            gitignore.write_text(GITIGNORE, encoding="utf-8")
            steps.append((".gitignore", "created"))

    except Abort as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    width = max(len(label) for label, _ in steps)
    print("\nVault bootstrapped\n")
    for label, detail in steps:
        print(f"  {label.ljust(width)}  {detail}")

    print(
        f"""
Next steps

  1. Obsidian: "Open folder as vault" and select
     {vault}

  2. Start your agent from the vault root -- the skill resolves raw/ and wiki/
     relative to the working directory, so always launch from there:

       cd {vault}
       claude            # or: gemini, opencode, pi, hermes
       hermes skills trust    # Hermes only, once per vault
                              # Pi: trust the project when it asks

  3. Ask it to ingest something, or drop old notes and files into +/ and
     organize them:

       /ingest https://example.com/post
       /organize

     /vault-status gives a one-screen health check. All four commands work in
     all five agents.

  4. Read {GUIDE_TARGET.as_posix()} in Obsidian. It is the folder, tag, and
     naming charter both you and the agent follow -- edit it there as your
     vault grows. GUIDE.html is the same charter, styled, for your browser.

  5. Fill in HOME.md (your focus and key notes) and ME.md (who you are and how
     you like to work). The agent reads both before every task and suggests
     additions, but only you edit them.

Customization goes in {installed_in}/{skill_root.name}/SKILL.md so your rules
travel with the skill. After updating the skill, re-run this script to
re-sync the commands in every agent. See references/obsidian-conventions.md for the
Obsidian-specific conventions worth adding.
"""
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
